### ISSUE TITLE
Stylish Errors

### ISSUE THREAD

**Issue by Cyber5imon** [Bloc67/Sonarr-Dark-Style#1]
When pasting the Sonarr3DarkStyle.css into Stylish, it shows the following errors:

warning | 1 | : | 1 | Rule is empty.
error | 2 | : | 2 | Expected RBRACE
error | 3 | : | 2 | Expected RBRACE
error | 4 | : | 2 | Expected RBRACE
error | 5 | : | 2 | Expected RBRACE
error | 6 | : | 2 | Expected RBRACE
error | 7 | : | 2 | Expected RBRACE
error | 8 | : | 2 | Expected RBRACE
error | 9 | : | 2 | Expected RBRACE
error | 10 | : | 2 | Expected RBRACE
error | 11 | : | 2 | Expected RBRACE
warning | 13 | : | 1 | The universal selector (*) is known to be slow.
warning | 14 | : | 5 | Use of !important
warning | 15 | : | 5 | Expected (<color> \| inherit) but found 'var(--txtcolor)'.
warning | 16 | : | 5 | Use of !important
warning | 17 | : | 5 | Use of !important

It seems it doesn't like any line with a double hyphen (--)...

Any thoughts?

**Comment by Bloc67** [comment]
Yes, use Stylus. :) Seriously though, I haven't looked at it for some time but its been working good in my Stylus for the last 20+ updates of Sonarr. I will upload a version without the use of CSS variables, that should make it work in Stylish.

**Comment by Bloc67** [comment]
Ok, updated the dark style to not use css variables. Let me know if it still gives errors in Stylish,

**Comment by Cyber5imon** [comment]
Works perfectly, no errors. Thank you!

**Comment by Cyber5imon** [comment]
When moving to another menu selection in Sonarr, say clicking on Activity, the css is removed. I have to manually refresh each time a click a menu selection. Do you experience the same behavior? Any ideas on how to get around this problem?

**Comment by Bloc67** [comment]
Just checked with Stylish, it shows no problem in my browser. 

Have you checked the line where it says where to show the style? You should use "URLs starting with" and http://localhost:8989/ as the value - unless you are using a different port.
